-- --------- 
-- BBDD
-- DB CICLISTAS
-- LUCAS HERRERA MORENO
-- ----------

CREATE DATABASE IF NOT EXISTS CICLISTAS;
USE CICLISTAS;

-- CICLISTAS

CREATE TABLE CICLISTAS(
	ID 	INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100),
    EDAD INT
);

DESC CICLISTAS;

CREATE TABLE EQUIPOS(
	ID INT PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    PRESUPUESTO DECIMAL(5,2),
    ID_DIRECTOR INT
);

DESC EQUIPOS;

CREATE TABLE CICLISTAS_EQUIPOS(
	ID_EQUIPO INT,
    ID_CICLISTA INT,
    AÑO_CONTRATO INT,
    CONSTRAINT CE_PK PRIMARY KEY(ID_EQUIPO,ID_CICLISTA)
);

DESC CICLISTAS_EQUIPOS;

CREATE TABLE DIRECTORES(
	ID INT,
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(100),
    ANTIGUEDAD INT
);

DESC DIRECTORES;

CREATE TABLE PATROCINADORES(
	ID INT,
    NOMBRE VARCHAR(100),
    NACIONALIDAD VARCHAR(80)
);

DESC PATROCINADORES;

CREATE TABLE PATROCINADOREQUIPO(
	ID_PATROCINADOR INT,
    ID_EQUIPO INT,
    NACIONALIDAD VARCHAR(20),
    CONSTRAINT PE_PK PRIMARY KEY(ID_PATROCINADOR,ID_EQUIPO)
);

DESC PATROCINADOREQUIPO;

SHOW TABLES;

ALTER TABLE CICLISTAS MODIFY APELLIDOS VARCHAR(50);
ALTER TABLE CICLISTAS MODIFY EDAD INT CHECK (EDAD>=18 AND EDAD<= 50);

DESC CICLISTAS;

ALTER TABLE EQUIPOS MODIFY PRESUPUESTO DECIMAL(8,2) DEFAULT(5000);
ALTER TABLE EQUIPOS ADD CONSTRAINT DIR_FK FOREIGN KEY(ID_DIRECTOR) REFERENCES DIRECTORES(ID) ON DELETE CASCADE ON UPDATE CASCADE;

DESC EQUIPOS;

ALTER TABLE CICLISTAS_EQUIPOS ADD CONSTRAINT EQU_FK FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPOS(ID) ON DELETE CASCADE ON UPDATE CASCADE;

DESC CICLISTAS_EQUIPOS;

ALTER TABLE DIRECTORES MODIFY APELLIDOS VARCHAR(50), ADD CONSTRAINT ANTIGUEDAD_CK CHECK (ANTIGUEDAD <= 10);

DESC DIRECTORES;

ALTER TABLE PATROCINADORES MODIFY NACIONALIDAD VARCHAR(30) DEFAULT "ESPAÑOLA";

ALTER TABLE PATROCINADOREQUIPO
ADD CONSTRAINT EQU2_FK FOREIGN KEY(ID_EQUIPO)
REFERENCES EQUIPOS(ID) ON DELETE CASCADE ON UPDATE CASCADE,

ADD CONSTRAINT PAT_FK FOREIGN KEY(ID_PATROCINADOR)
REFERENCES PATROCINADORES(ID) ON DELETE CASCADE ON UPDATE CASCADE;

DESC PATROCINADORES;