-- ----------------------------
-- LUCAS HERRERA
-- BBDD
-- ------------------------------

CREATE DATABASE TEMA7;
USE TEMA7;

CREATE TABLE ALUMNOS(
	ID_ALUMNO INT PRIMARY KEY,
    NOMBRE VARCHAR(20),
    POBLACION VARCHAR(20) DEFAULT 'PLASENCIA'
);

DESC ALUMNOS;

SELECT * FROM ALUMNOS;

INSERT INTO ALUMNOS VALUES ('1', 'ALUMNO1', 'CACERES');

INSERT INTO ALUMNOS VALUES ('2', 'ALUMNO2', 'CACERES'),('3', 'ALUMNO3', 'CACERES');

INSERT INTO ALUMNOS (ID_ALUMNO,NOMBRE) VALUES ('4','ALUMNO4');

INSERT INTO ALUMNOS (ID_ALUMNO,POBLACION) VALUES ('6','CC');

INSERT INTO ALUMNOS VALUES (7,NULL,'CC');

INSERT INTO ALUMNOS VALUES (8,NULL,DEFAULT);

INSERT INTO ALUMNOS (POBLACION,ID_ALUMNO,NOMBRE) VALUES (DEFAULT,9,'NOSE');

CREATE TABLE ALUMNOS2(
	ID_ALUMNO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20),
    POBLACION VARCHAR(20) DEFAULT 'PLASENCIA'
);

DESC ALUMNOS2;

INSERT INTO ALUMNOS2 VALUES (1,'ALUMNO1','CC');

CREATE TABLE DEPARTAMENTOS(
	ID INT PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

CREATE TABLE EMPLEADOS(
	ID INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    ID_DEPARTAMENTO INT,
    CONSTRAINT DEP_FK FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO DEPARTAMENTOS VALUES (1, 'CONTABILIDAD'), (2, 'RECURSOS HUMANOS'), (3,'INFORMATICA');
INSERT INTO DEPARTAMENTOS VALUES (4,'VENTAS');

INSERT INTO EMPLEADOS VALUES (101,'ANA LOPEZ', 1), 
(102, 'CARLOS MARTIN', 3), (103, 'LUCIA GARCIA', 2), (104, 'JAVIER PEREZ',3),  (105,'MARIA SERRANO',1);

UPDATE DEPARTAMENTOS SET ID=20 WHERE ID=2;

