-- --------------------
-- LUCAS HERRERA MORENO
-- BASE DE DATOS
-- 1 DAM
-- ----------------------

CREATE DATABASE ORGANIZACION;
USE ORGANIZACION;

CREATE TABLE EMPLEADOS(
	NUM_EMPLEADO INT PRIMARY KEY,
    APELLIDO VARCHAR(50),
    OFICIO VARCHAR(50),
    DIRECCION VARCHAR(50),
    FECHA_ALTA DATE,
    SALARIO DECIMAL(10,2),
    COMISION DECIMAL (4,2),
    NUM_DPTO INT
);

DESC EMPLEADOS;

CREATE TABLE DEPARTAMENTO(
	NUM_DPTO INT PRIMARY KEY,	
    NOMBRE VARCHAR(50),
    LOCALIDAD VARCHAR(50)	
);

ALTER TABLE EMPLEADOS MODIFY APELLIDO VARCHAR(50) NOT NULL;
ALTER TABLE EMPLEADOS MODIFY OFICIO VARCHAR(50) NOT NULL;
ALTER TABLE EMPLEADOS MODIFY SALARIO DECIMAL(10,2) NOT NULL;
ALTER TABLE EMPLEADOS MODIFY NUM_DPTO INT NOT NULL;

ALTER TABLE EMPLEADOS MODIFY APELLIDO VARCHAR(50) NOT NULL UNIQUE;

ALTER TABLE EMPLEADOS MODIFY SALARIO DECIMAL(10,2) NOT NULL CHECK (SALARIO > 0);

ALTER TABLE EMPLEADOS MODIFY COMISION DECIMAL(4,2) CHECK (COMISION BETWEEN 2 AND 15);

ALTER TABLE EMPLEADOS MODIFY APELLIDO VARCHAR(50) NOT NULL;

ALTER TABLE EMPLEADOS ADD CONSTRAINT DEP_FK FOREIGN KEY(NUM_DPTO) REFERENCES DEPARTAMENTO(NUM_DPTO) ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO EMPLEADOS VALUES 
	(1,'GARCIA','PROGRAMADOR','CALLE 1','2000-01-01','1500.60','5.25',10),
    (2,'PEREZ','PROGRAMADOR','CALLE 1','2015-01-01','1500.60','2.5',20),
    (3,'LORCA','ADMINISTRADOR','CALLE 2','2002-01-01','1500.60','14.25',30),
    (4,'MARTINEZ','ANALISTA','CALLE SN','2020-01-01','1500.60','5.25',10),
    (5,'HERNANDEZ','PROGRAMADOR','CALLE 1','2010-01-01','1500.60','5.25',40);
    
INSERT INTO DEPARTAMENTO VALUES
	(10,'CONTABILIDAD','SEVILLA'),
    (20,'INVESTIGACION','MADRID'),
    (30,'VENTAS','BARCELONA'),
    (40,'PRODUCCION','BILBAO');

SELECT * FROM DEPARTAMENTO;

ALTER TABLE EMPLEADOS MODIFY COMISION DECIMAL(4,2) DEFAULT '10.0';

ALTER TABLE DEPARTAMENTO MODIFY NOMBRE VARCHAR(50) NOT NULL, MODIFY LOCALIDAD VARCHAR(50) NOT NULL;

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT LOCALIDADES CHECK(LOCALIDAD IN('SEVILLA','MADRID','BARCELONA','BILBAO'));

DROP TABLE TIENDAS;

CREATE TABLE TIENDAS(
	DNI VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(20),
    POBLACION VARCHAR(20),
    PROVINCIA VARCHAR(20),
    CODPOSTAL VARCHAR(5)
);

ALTER TABLE TIENDAS MODIFY NOMBRE VARCHAR(30) NOT NULL;
ALTER TABLE TIENDAS MODIFY PROVINCIA VARCHAR(20) DEFAULT 'CACERERES';
ALTER TABLE TIENDAS MODIFY CODPOSTAL VARCHAR(5) NOT NULL; 

DESC TIENDAS;
SHOW TABLES;

INSERT INTO TIENDAS VALUES
	('11111111A','ANA','1000',DEFAULT,'10600'),
    ('11111111B','MARIA','1000',DEFAULT,'10600'),
    ('11111111C','JUAN','1000',DEFAULT,'10600');
    
UPDATE TIENDAS SET CODPOSTAL='10000';

DELETE FROM TIENDAS WHERE NOMBRE='ANA';

ALTER TABLE TIENDAS DROP COLUMN DIRECCION;
DESC TIENDAS;

CREATE INDEX APELLIDO_I ON EMPLEADOS(APELLIDO);
ALTER TABLE EMPLEADOS DROP INDEX APELLIDO_I;


