-- --------------------------------
-- DAM 1 DDBB
-- PRACTICA 2
-- LUCAS HERRERA
-- 25-26
-- -------------------

CREATE DATABASE IF NOT EXISTS PRACTICA2;
USE PRACTICA2;

CREATE TABLE ESTUDIANTES(
	ID_ESTUDIANTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    CORREO VARCHAR(100) UNIQUE,
    FECHA_NACIMIENTO DATE,
    ACTIVO BOOLEAN
);

DESC ESTUDIANTES;

CREATE TABLE INSTRUCTORES(
	ID_INSTRUCTOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    ESPECIALIDAD VARCHAR(100),
    SALARIO DECIMAL(4,2)
);

DESC INSTRUCTORES;

CREATE TABLE CURSOS(
	ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
    ID_INSTRUCTOR INT,
    TITULO VARCHAR(150),
    DESCRIPCION VARCHAR(500),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    CONSTRAINT INS_ID_FK FOREIGN KEY(ID_INSTRUCTOR) REFERENCES INSTRUCTORES(ID_INSTRUCTOR)
);

DESC CURSOS;

CREATE TABLE INSCRIPCIONES(
	INSCRIPCION_ID INT AUTO_INCREMENT PRIMARY KEY,
    ESTUDIANTE_ID INT,
    CURSO_ID INT,
    FECHA_INSCRIPCION DATE,
    CONSTRAINT EST_FK FOREIGN KEY(ESTUDIANTE_ID) REFERENCES ESTUDIANTES(ID_ESTUDIANTE) ON  DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CUR_FK FOREIGN KEY(CURSO_ID) REFERENCES CURSOS(ID_CURSO)
);