-- ------------------------
-- LUCAS HERRERA MORENO
-- BASE DE DATOS
-- EJERCICIO REPASO DDL Y DML
-- --------------------------

CREATE DATABASE REPASO;
USE REPASO;

CREATE TABLE EMPLEADOS(
	DNI CHAR(9),
    NOMBRE VARCHAR(10),
    APELLIDO1 VARCHAR(15),
    APELLIDO2 VARCHAR(15),
    DIRECC1 VARCHAR(25),
    DIRECC2 VARCHAR(20),
    CIUDAD VARCHAR(20),
    PROVINCIA VARCHAR(20),
    CODPOSTAL CHAR(5),
    SEXO CHAR(1),
    FECHA_NAC DATE
);

CREATE TABLE ESTUDIOS(
	EMPLEADO_DNI CHAR(9),
    UNIVERSIDAD INT,
    AÑO INT,
    GRADO VARCHAR(3),
    ESPECIALIDAD VARCHAR(20)
);

CREATE TABLE UNIVERSIDADES(
	COD_UNIV INT,
    NOMBRE_UNIV VARCHAR(25),
    CIUDAD VARCHAR(20),
    MUNICIPIO VARCHAR(2),
    CODPOSTAL CHAR(5)
);

CREATE TABLE TRABAJOS(
	COD_TRABAJO INT,
    NOMBRE_TRAB VARCHAR(20),
    SALARIO_MIN DECIMAL(10,2),
    SALARIO_MAX DECIMAL(10,2)
);

CREATE TABLE DEPARTAMENTOS(
	COD_DPTO INT,
    NOMBRE_DPTO VARCHAR(30),
    DPTO_PADRE INT,
    PRESUPUESTO DECIMAL(10,2),
    PRES_ACTUAL DECIMAL(10,2)
);

CREATE TABLE HISTORIAL_LABORAL(
	DNI_EMPLEADO CHAR(9),
    COD_TRABAJO INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    COD_DPTO INT,
    DNI_SUPERVISOR INT
);

CREATE TABLE HISTORIAL_SALARIAL(
	DNI_EMPLEADO CHAR(9),
    SALARIO DECIMAL(10,2),
    FECHA_COMIENZO DATE,
    FECHA_FIN DATE
);

ALTER TABLE EMPLEADOS MODIFY NOMBRE VARCHAR(10) NOT NULL;
ALTER TABLE UNIVERSIDADES MODIFY NOMBRE_UNIV VARCHAR(25) NOT NULL;
ALTER TABLE TRABAJOS MODIFY NOMBRE_TRAB VARCHAR(20) NOT NULL;
ALTER TABLE DEPARTAMENTOS MODIFY NOMBRE_DPTO VARCHAR(30) NOT NULL;

ALTER TABLE EMPLEADOS MODIFY APELLIDO1 VARCHAR(15) NOT NULL;

ALTER TABLE DEPARTAMENTOS MODIFY PRESUPUESTO DECIMAL(10,2) NOT NULL;

ALTER TABLE HISTORIAL_SALARIAL MODIFY SALARIO DECIMAL(10,2) NOT NULL;

ALTER TABLE TRABAJOS MODIFY SALARIO_MIN DECIMAL(10,2) NOT NULL,
						MODIFY SALARIO_MAX DECIMAL(10,2) NOT NULL;
                        
ALTER TABLE TRABAJOS MODIFY NOMBRE_TRAB VARCHAR(20) UNIQUE;
ALTER TABLE DEPARTAMENTOS MODIFY NOMBRE_DPTO VARCHAR(30) UNIQUE;

ALTER TABLE EMPLEADOS ADD CONSTRAINT DNI_PK PRIMARY KEY(DNI);

ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT COD_PK PRIMARY KEY(COD_DPTO);
ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT DPDRE_FK FOREIGN KEY(DPTO_PADRE) REFERENCES DEPARTAMENTOS(COD_DPTO) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ESTUDIOS ADD CONSTRAINT EST_PK PRIMARY KEY(EMPLEADO_DNI,UNIVERSIDAD,ESPECIALIDAD);
ALTER TABLE ESTUDIOS ADD CONSTRAINT EMP_FK FOREIGN KEY(EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE UNIVERSIDADES ADD CONSTRAINT COD_UNI_PK PRIMARY KEY(COD_UNIV);

ALTER TABLE ESTUDIOS ADD CONSTRAINT UNI_FK FOREIGN KEY(UNIVERSIDAD) REFERENCES UNIVERSIDADES(COD_UNIV) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE HISTORIAL_LABORAL ADD CONSTRAINT HIST_PK PRIMARY KEY(DNI_EMPLEADO,COD_TRABAJO,FECHA_INICIO);

ALTER TABLE HISTORIAL_LABORAL ADD CONSTRAINT EMP2_FK FOREIGN KEY(DNI_EMPLEADO) REFERENCES EMPLEADOS(DNI) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE HISTORIAL_LABORAL MODIFY DNI_SUPERVISOR CHAR(9);
ALTER TABLE HISTORIAL_LABORAL ADD CONSTRAINT SUP_FK FOREIGN KEY(DNI_SUPERVISOR) REFERENCES EMPLEADOS(DNI) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE TRABAJOS ADD CONSTRAINT TRA_PK PRIMARY KEY(COD_TRABAJO);

ALTER TABLE HISTORIAL_LABORAL ADD CONSTRAINT TRA_FK FOREIGN KEY(COD_TRABAJO) REFERENCES TRABAJOS(COD_TRABAJO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE HISTORIAL_LABORAL ADD CONSTRAINT DPTO_FK FOREIGN KEY(COD_DPTO) REFERENCES DEPARTAMENTOS(COD_DPTO) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE HISTORIAL_SALARIAL ADD CONSTRAINT DNI_PK PRIMARY KEY(DNI_EMPLEADO,SALARIO,FECHA_COMIENZO);

ALTER TABLE HISTORIAL_SALARIAL ADD CONSTRAINT DNI_FK FOREIGN KEY(DNI_EMPLEADO) REFERENCES EMPLEADOS(DNI) ON UPDATE CASCADE ON DELETE CASCADE;

INSERT INTO EMPLEADOS (NOMBRE,APELLIDO1,APELLIDO2,DNI,SEXO) VALUES ('Sergio','Palma','Entrena','111222','P'),('Lucia','Ortega','Plus','222333','');

INSERT INTO TRABAJOS VALUES (1,'PROGRAMADOR','),();