-- -----------------------
-- BD DDL1
-- BBDD 25-26
-- Lucas Herrera
-- -----------------------

-- 1. Crea la base de datos DDL1, que tendrá las siguientes tablas:

CREATE DATABASE DDL1;
USE DDL1;

CREATE TABLE COMERCIAL(
	ID INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO_1 VARCHAR(100) NOT NULL,
    APELLIDO_2 VARCHAR(100),
    CIUDAD VARCHAR(100), 
    COMISION FLOAT
);

CREATE TABLE CLIENTE(
	ID INT PRIMARY KEY,
    NOMBRE VARCHAR(25), 
    PRIMER_APELLIDO VARCHAR(15) NOT NULL,
    CIUDAD VARCHAR(25),
    CATEGORIA INT
);

-- Modifica la columna nombre de la tabla cliente para que pueda almacenar cadenas de hasta 100 caracteres y para que no pueda ser NULL.
ALTER TABLE CLIENTE MODIFY NOMBRE VARCHAR(100) NOT NULL;

-- Modifica el nombre de la columna primer_apellido y llámala apellido1. Permitir también que pueda almacenar hasta 100 caracteres y que no pueda ser un valor NULL.
ALTER TABLE CLIENTE RENAME COLUMN PRIMER_APELLIDO TO APELLIDO1;
ALTER TABLE CLIENTE MODIFY APELLIDO1 VARCHAR(100) NOT NULL;

SHOW TABLES;
DESCRIBE CLIENTE;

ALTER TABLE CLIENTE MODIFY NOMBRE VARCHAR(100) NOT NULL;

ALTER TABLE CLIENTE ADD APELLIDO2 VARCHAR(100) AFTER APELLIDO1;
ALTER TABLE CLIENTE DROP CATEGORIA;

CREATE TABLE ALUMNOS(
	ID_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
	DNI CHAR(9),
    NOMBRE VARCHAR(50)
);

INSERT INTO ALUMNOS (DNI,NOMBRE,POBLACION) VALUES ('111A','PEPE', 'MADRID'), ('222A','MARIA', 'CACERES');
INSERT INTO ALUMNOS (DNI,NOMBRE,POBLACION) VALUES (NULL,NULL, 'MADRID');

SELECT * FROM ALUMNOS;

ALTER TABLE ALUMNOS ADD POBLACION VARCHAR(50) DEFAULT 'PLASENCIA';

ALTER TABLE ALUMNOS MODIFY DNI CHAR(9) NOT NULL;

ALTER TABLE ALUMNOS ADD CONSTRAINT ALU_PK PRIMARY KEY(DNI);
ALTER TABLE ALUMNOS ADD CONSTRAINT TEL_UK UNIQUE(TELEFONO);
ALTER TABLE ALUMNOS MODIFY NOMBRE VARCHAR(100) NOT NULL;

CREATE TABLE MATRICULAS(
	ID_ALUMNO INT,
    ID_MODULO INT,
    FECHA_MATRICULA DATE,
    CONSTRAINT MAT_PK PRIMARY KEY(ID_ALUMNO,ID_MODULO)
);

ALTER TABLE MATRICULAS ADD CONSTRAINT MAT_PL PRIMARY KEY(ID_ALUMNO, ID_MODULO);

DESC MATRICULAS;

ALTER TABLE MATRICULAS ADD CONSTRAINT ALU_FK FOREIGN KEY(ID_ALUMNO) REFERENCES ALUMNOS(ID_ALUMNOS) ON UPDATE CASCADE ON DELETE CASCADE;

DESC ALUMNOS;

CREATE DATABASE PRUEBA;
USE PRUEBA;