-- ------------------------------
-- LUCAS HERRERA MORENO
-- BASE DE DATOS
-- CONSULTAS Y SELET
-- ----------------------------

CREATE DATABASE TEMA6;
USE TEMA6;

CREATE TABLE ALUMNOS(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO1 VARCHAR(100) NOT NULL,
    APELLIDO2 VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    ES_REPETIDOR ENUM('si','no'),
    TELEFONO VARCHAR(9)
);

DROP TABLE CURSOS;

CREATE TABLE CURSOS(
	ID_CURSO INT PRIMARY KEY,
    NOMBRE VARCHAR(20),
    DURACION INT
);

INSERT INTO CURSOS VALUES 
(1,'CURSO 1', 2),
(2, 'CURSO 2', 1),
(3, 'CURSO 3', 2),
(4, 'CURSO 4', 3);

SELECT * FROM CURSOS;

ALTER TABLE ALUMNOS ADD COLUMN ID_CURSO INT;

DESC ALUMNOS;

ALTER TABLE ALUMNOS ADD CONSTRAINT CURS_FK FOREIGN KEY(ID_CURSO) REFERENCES CURSOS(ID_CURSO) ON UPDATE CASCADE ON DELETE CASCADE;

UPDATE ALUMNOS SET ID_CURSO=1 WHERE ID IN(1,2,3,4);
UPDATE ALUMNOS SET ID_CURSO=2 WHERE ID IN(5,6,7,8);
UPDATE ALUMNOS SET ID_CURSO=3 WHERE ID IN(9,10);

-- ----------------------------------------------------------------

SELECT ID_NOMBRE,NOMBRE FROM ALUMNOS,CURSOS;

SELECT ID,ALUMNOS.NOMBRE,CURSOS.NOMBRE
FROM ALUMNOS INNER JOIN CURSOS
ON ALUMNOS.ID_CURSO=CURSOS.ID_CURSO
WHERE ALUMNOS.ID_CURSO=1 AND ALUMNOS.NOMBRE='MARIA';

SELECT ID,ALUMNOS.NOMBRE,CURSOS.NOMBRE
FROM ALUMNO INNER JOIN CURSOS
USING (ID_CURSO);

CREATE TABLE AULAS(
	ID_AULA INT PRIMARY KEY,
    NOMBRE VARCHAR(30),
    METROS_CUADRADOS FLOAT
);

INSERT INTO AULAS VALUES
(101,'AULA PRINCIPAL', '90.64'), (102,'AULA BACHILLERATO', '85.75'), (201,'AULA DAM', '57.25'), (218,'AULA PLANTA2', '50');

SELECT * FROM AULAS;

ALTER TABLE CURSOS ADD COLUMN ID_AULA INT;
ALTER TABLE CURSOS ADD CONSTRAINT AULA_FK FOREIGN KEY(ID_AULA) REFERENCES AULAS(ID_AULA) ON UPDATE CASCADE ON DELETE CASCADE;

UPDATE CURSOS SET ID_AULA=101 WHERE ID_CURSO=1;
UPDATE CURSOS SET ID_AULA=102 WHERE ID_CURSO=2;
UPDATE CURSOS SET ID_AULA=201 WHERE ID_CURSO=3;
UPDATE CURSOS SET ID_AULA=218 WHERE ID_CURSO=4;

SELECT ID,ALUMNOS.NOMBRE,CURSOS.NOMBRE,AULAS.NOMBRE
FROM ALUMNOS INNER JOIN CURSOS
ON ALUMNOS.ID_CURSO=CURSOS.ID_CURSO
INNER JOIN AULAS
ON CURSOS.ID_AULA=AULAS.ID_AULA
WHERE CURSOS.ID_CURSO IN(1,2);

INSERT INTO ALUMNOS VALUES (1, 'MARÍA', 'SÁNCHEZ', 'PÉREZ', '1990-12-01', 'NO', NULL), 
(2, 'JUAN', 'SÁEZ', 'VEGA', '1998-04-02', 'NO', 618253876), 
(3, 'PEPE', 'RAMÍREZ', 'GEA', '1988-01-03', 'NO', NULL), 
(4, 'LUCÍA', 'SÁNCHEZ', 'ORTEGA', '1993-06-13', 'SI', 678516294), 
(5, 'PACO', 'MARTÍNEZ', 'LÓPEZ', '1995-11-24', 'NO', 692735409), 
(6, 'IRENE', 'GUTIÉRREZ', 'SÁNCHEZ', '1991-03-28', 'SI', NULL), 
(7, 'CRISTINA', 'FERNÁNDEZ', 'RAMÍREZ', '1996-09-17', 'NO', 628349590),
 (8, 'ANTONIO', 'CARRETERO', 'ORTEGA', '1994-05-20', 'SI', 612345633),
 (9, 'MANUEL', 'DOMÍNGUEZ', 'HERNÁNDEZ', '1999-07-08', 'NO', NULL),
 (10, 'DANIEL', 'MORENO', 'RUIZ', '1998-02-03', 'NO', NULL);

SELECT NOMBRE AS NOMBRE_ALUMNO FROM ALUMNO;

SELECT NOMBRE,FECHA_NACIMIENTO FROM ALUMNO WHERE APELLIDO1='SÁNCHEZ' AND APELLIDO2='PÉREZ' AND ES_REPETIDOR='NO';

SELECT * FROM ALUMNOS;
SELECT * FROM AULAS;
SELECT * FROM CURSOS;

SELECT NOMBRE, APELLIDO1 FROM ALUMNOS;