-- ---------------------------------------------------
-- primera base de datos
-- dam 25-26
-- lucas herrera
-- ---------------------------------------------------

CREATE DATABASE MI_PRIMERA_BASE_DE_DATOS;

SHOW DATABASES;

USE MI_PRIMERA_BASE_DE_DATOS;

CREATE TABLE ALUMNOS(
	COD_ALUMNO INT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE
);

DESCRIBE ALUMNOS;

ALTER TABLE ALUMNOS RENAME TO EMP;
ALTER TABLE EMP RENAME TO ALUMNOS;

ALTER TABLE ALUMNOS ADD POBLACION VARCHAR(40) NOT NULL;
ALTER TABLE ALUMNOS ADD APELLIDOS VARCHAR(50) AFTER NOMBRE;
ALTER TABLE ALUMNOS MODIFY POBLACION VARCHAR(40) NOT NULL AFTER COD_ALUMNO;
ALTER TABLE ALUMNOS DROP POBLACION;	

DROP TABLE ALUMNOS;

SHOW TABLES;

ALTER TABLE CLIENTE MODIFY NOMBRE VARCHAR(100) NOT NULL; 

