-- ---------------------
-- LUCAS HERRERA MORENO
-- 16/3/26
-- PRACTICA EVALUABLE TEMA 5/7
-- ---------------------

-- CREACION Y CONEXION A BASE DE DATOS
CREATE DATABASE DAM_DDL_LUCASHERRERA;
USE DAM_DDL_LUCASHERRERA;

-- DDL

-- SERIES
CREATE TABLE SERIES(
	COD_SERIE INT UNSIGNED AUTO_INCREMENT,
    NOM_SERIE CHAR(50),
    GENERO VARCHAR(20) NOT NULL,
    FECHA_ESTRENO DATE NOT NULL,
    PRIMARY KEY(COD_SERIE)
);

-- ACTORES
CREATE TABLE ACTORES(
	COD_ACTOR INT,
    NOMBRE_ACTOR VARCHAR(50),
    EDAD INT,
    NACIONALIDAD VARCHAR(50),
    PRIMARY KEY(COD_ACTOR)
);

-- TEMPORADA
CREATE TABLE TEMPORADA(
	COD_SERIE INT,
    NUM_TEMPORADA INT,
    FECHA_ESTRENO DATE,
    PRIMARY KEY(COD_SERIE,NUM_TEMPORADA)
);

-- SERIEACTOR
CREATE TABLE SERIEACTOR(
	COD_SERIE INT,
    COD_ACTOR INT,
    PRIMARY KEY(COD_SERIE,COD_ACTOR)
);

-- 3.1
ALTER TABLE SERIES MODIFY NOM_SERIE CHAR(50) UNIQUE;

-- 3.2
ALTER TABLE SERIES ADD CONSTRAINT GENERO_CK CHECK (GENERO IN ('DRAMA', 'COMEDIA','FANTASÍA','CIENCIA FICCIÓN'));

-- 3.3
ALTER TABLE SERIES RENAME COLUMN FECHA_ESTRENO TO AÑO_ESTRENO;

-- 3.4
ALTER TABLE SERIES RENAME COLUMN NOM_SERIE TO NOMBRE_SERIE;
ALTER TABLE SERIES MODIFY NOMBRE_SERIE VARCHAR(100);

-- 4.1
ALTER TABLE ACTORES MODIFY EDAD INT NOT NULL;
ALTER TABLE ACTORES ADD CONSTRAINT EDAD_CK CHECK (EDAD >= 0);

-- 4.2
ALTER TABLE ACTORES ADD COLUMN FECHA_NACIMIENTO VARCHAR(50) AFTER NOMBRE_ACTOR;

-- 4.3
ALTER TABLE ACTORES ALTER NACIONALIDAD SET DEFAULT 'ESPAÑOLA';

-- 4.4
ALTER TABLE ACTORES DROP COLUMN EDAD;

-- 5.1
CREATE TABLE PLATAFORMAS(
	COD_PLATAFORMA INT,
    NOMBRE_PLATAFORMA VARCHAR(50) NOT NULL,
    PRIMARY KEY(COD_PLATAFORMA)
);

-- 5.2
ALTER TABLE SERIEACTOR ADD CONSTRAINT SERIE_FK FOREIGN KEY(COD_SERIE) REFERENCES SERIES(COD_SERIE) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE SERIEACTOR ADD CONSTRAINT ACTOR_FK FOREIGN KEY(COD_ACTOR) REFERENCES ACTORES(COD_ACTOR) ON UPDATE CASCADE ON DELETE CASCADE;

-- 5.3
ALTER TABLE TEMPORADA MODIFY COD_SERIE INT UNSIGNED AUTO_INCREMENT;
ALTER TABLE TEMPORADA ADD CONSTRAINT SERIE_FK FOREIGN KEY(COD_SERIE) REFERENCES SERIES(COD_SERIE);

-- 5.4
CREATE TABLE SERIEPLATAFORMA(
	COD_SERIE INT,
    COD_PLATAFORMA INT,
    FECHA_INCLUSION DATE,
    PRIMARY KEY(COD_SERIE, COD_PLATAFORMA)
);

ALTER TABLE SERIEPLATAFORMA MODIFY COD_SERIE INT UNSIGNED AUTO_INCREMENT;
ALTER TABLE SERIEPLATAFORMA ADD CONSTRAINT SERIE2_FK FOREIGN KEY(COD_SERIE) REFERENCES SERIES(COD_SERIE) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SERIEPLATAFORMA ADD CONSTRAINT PLAT_FK FOREIGN KEY(COD_PLATAFORMA) REFERENCES PLATAFORMAS(COD_PLATAFORMA) ON UPDATE CASCADE ON DELETE CASCADE;

-- Como la PK de la tabla series no coincide con las FK con las cuales estamos intentando relacionarla,
-- ya que la PK de series es UNSIGNED y AUTO_INCREMENT, hay que modificar las FK que queramos relacionarç
-- con series

-- 6.1
ALTER TABLE SERIEPLATAFORMA ADD CONSTRAINT FECHA_CK CHECK (FECHA_INCLUSION BETWEEN '2000-0-0' AND '2005-31-12');

-- 6.2
ALTER TABLE TEMPORADA MODIFY FECHA_ESTRENO TIMESTAMP;

-- 6.3
RENAME TABLE ACTORES TO PERSONAJES;

-- 6.4
DROP TABLE IF EXISTS SERIEPLATAFORMA;