-- ---------------------
-- LUCAS HERRERA MORENO
-- 16/3/26
-- PRACTICA EVALUABLE TEMA 5/7
-- ---------------------

-- CREACION Y CONEXION A BASE DE DATOS
CREATE DATABASE DAM_DDL_LUCASHERRERA;
USE DAM_DDL_LUCASHERRERA;

DROP DATABASE DAM_DDL_LUCASHERRERA;

-- DDL

-- SERIES
CREATE TABLE SERIES(
	COD_SERIE INT UNSIGNED AUTO_INCREMENT,
    NOM_SERIE CHAR(50),
    GENERO VARCHAR(20) NOT NULL,
    FECHA_ESTRENO DATE NOT NULL,
    PRIMARY KEY(COD_SERIE)
);

-- ACTORES
CREATE TABLE ACTORES(
	COD_ACTOR INT,
    NOMBRE_ACTOR VARCHAR(50),
    EDAD INT,
    NACIONALIDAD VARCHAR(50),
    PRIMARY KEY(COD_ACTOR)
);

-- TEMPORADA
CREATE TABLE TEMPORADA(
	COD_SERIE INT,
    NUM_TEMPORADA INT,
    FECHA_ESTRENO DATE,
    PRIMARY KEY(COD_SERIE,NUM_TEMPORADA)
);

-- SERIEACTOR
CREATE TABLE SERIEACTOR(
	COD_SERIE INT,
    COD_ACTOR INT,
    PRIMARY KEY(COD_SERIE,COD_ACTOR)
);

-- 3.1
ALTER TABLE SERIES MODIFY NOM_SERIE CHAR(50) UNIQUE;

-- 3.2
ALTER TABLE SERIES ADD CONSTRAINT GENERO_CK CHECK (GENERO IN ('DRAMA', 'COMEDIA','FANTASÍA','CIENCIA FICCIÓN'));

-- 3.3
ALTER TABLE SERIES RENAME COLUMN FECHA_ESTRENO TO AÑO_ESTRENO;

-- 3.4
ALTER TABLE SERIES RENAME COLUMN NOM_SERIE TO NOMBRE_SERIE;
ALTER TABLE SERIES MODIFY NOMBRE_SERIE VARCHAR(100);

-- 4.1
ALTER TABLE ACTORES MODIFY EDAD INT NOT NULL;
ALTER TABLE ACTORES ADD CONSTRAINT EDAD_CK CHECK (EDAD >= 0);

-- 4.2
ALTER TABLE ACTORES ADD COLUMN FECHA_NACIMIENTO VARCHAR(50) AFTER NOMBRE_ACTOR;

-- 4.3
ALTER TABLE ACTORES ALTER NACIONALIDAD SET DEFAULT 'ESPAÑOLA';

-- 4.4
ALTER TABLE ACTORES DROP COLUMN EDAD;

-- 5.1
CREATE TABLE PLATAFORMAS(
	COD_PLATAFORMA INT,
    NOMBRE_PLATAFORMA VARCHAR(50) NOT NULL,
    PRIMARY KEY(COD_PLATAFORMA)
);

-- 5.2
ALTER TABLE SERIEACTOR MODIFY COD_SERIE INT UNSIGNED AUTO_INCREMENT;
ALTER TABLE SERIEACTOR ADD CONSTRAINT SERIE_FK FOREIGN KEY(COD_SERIE) REFERENCES SERIES(COD_SERIE) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE SERIEACTOR ADD CONSTRAINT ACTOR_FK FOREIGN KEY(COD_ACTOR) REFERENCES ACTORES(COD_ACTOR) ON UPDATE CASCADE ON DELETE CASCADE;

-- 5.3
ALTER TABLE TEMPORADA MODIFY COD_SERIE INT UNSIGNED AUTO_INCREMENT;
ALTER TABLE TEMPORADA ADD CONSTRAINT SERIE2_FK FOREIGN KEY(COD_SERIE) REFERENCES SERIES(COD_SERIE);

-- 5.4
CREATE TABLE SERIEPLATAFORMA(
	COD_SERIE INT,
    COD_PLATAFORMA INT,
    FECHA_INCLUSION DATE,
    PRIMARY KEY(COD_SERIE, COD_PLATAFORMA)
);

ALTER TABLE SERIEPLATAFORMA MODIFY COD_SERIE INT UNSIGNED AUTO_INCREMENT;
ALTER TABLE SERIEPLATAFORMA ADD CONSTRAINT SERIE3_FK FOREIGN KEY(COD_SERIE) REFERENCES SERIES(COD_SERIE) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SERIEPLATAFORMA ADD CONSTRAINT PLAT_FK FOREIGN KEY(COD_PLATAFORMA) REFERENCES PLATAFORMAS(COD_PLATAFORMA) ON UPDATE CASCADE ON DELETE CASCADE;

-- Como la PK de la tabla series no coincide con las FK con las cuales estamos intentando relacionarla,
-- ya que la PK de series es UNSIGNED y AUTO_INCREMENT, hay que modificar las FK que queramos relacionarç
-- con series

-- 6.1
ALTER TABLE SERIEPLATAFORMA ADD CONSTRAINT FECHA_CK CHECK (FECHA_INCLUSION BETWEEN '2000-0-0' AND '2005-31-12');

-- 6.2
ALTER TABLE TEMPORADA MODIFY FECHA_ESTRENO TIMESTAMP;

-- 6.3
RENAME TABLE ACTORES TO PERSONAJES;

-- 6.4
DROP TABLE IF EXISTS SERIEPLATAFORMA;

-- INSERCIONES

-- 1.1 Inserta dos series en la tabla series

INSERT INTO SERIES (NOMBRE_SERIE, GENERO, AÑO_ESTRENO) VALUES 
('La Casa de Papel', 'DRAMA', '2017-05-02'),
('Stranger Things', 'CIENCIA FICCIÓN', '2016-07-15');

-- 1.2 Inserta dos actores (ahora PERSONAJES) y relacionalos con una de las series anteriores
INSERT INTO PERSONAJES (COD_ACTOR, NOMBRE_ACTOR, FECHA_NACIMIENTO, NACIONALIDAD)VALUES 
(10, 'Úrsula Corberó', '1989-08-11', 'ESPAÑOLA'),
(11, 'Álvaro Morte', '1975-02-23', 'ESPAÑOL');

INSERT INTO SERIEACTOR (COD_SERIE, COD_ACTOR)VALUES 
(5, 10),
(5, 11);

-- 1.3 Inserta dos temporadas para ua de las series creadas
INSERT INTO TEMPORADA (COD_SERIE, NUM_TEMPORADA, FECHA_ESTRENO)VALUES 
(5, 1, '2017-05-02'),
(5, 2, '2018-04-06');

-- ACTUALIZACIONES

-- 2.2 Modifica el nombre de un actor (en la tabla PERSONAJES)
UPDATE PERSONAJES
SET NOMBRE_ACTOR = 'Millie Bobby Brown'
WHERE NOMBRE_ACTOR = 'Milly Brown';

-- 2.3 Actualiza la fecha de estreno de una temporada
UPDATE TEMPORADA
SET FECHA_ESTRENO = '2020-07-15'
WHERE COD_SERIE = 5 AND NUM_TEMPORADA = 1;

-- BORRADOS 

-- 3.1 Elimina una serie que tenga temporadas asociadas
DELETE FROM TEMPORADA WHERE COD_SERIE = 5;
DELETE FROM SERIES WHERE COD_SERIE = 5;

-- 3.2 Elimina un actor (personaje) que este relacionado con una serie
DELETE FROM SERIEACTOR WHERE COD_ACTOR = 10;
DELETE FROM PERSONAJES WHERE COD_ACTOR = 10;

-- 3.3 Elimina todas las temporadas de una serie concreta sin borrar la serie
DELETE FROM TEMPORADA 
WHERE COD_SERIE = 5;

-- 3.4 Elimina una plataforma y explica que ocurre con la tabla SERIEPLATAFORMA
DELETE FROM PLATAFORMAS WHERE COD_PLATAFORMA = 3;

-- Como no existe un borrado en cascada, se borrará la plataforma pero quedarán registros en SERIEPLATAFORMA apuntando a plataformas que no existen

-- CONSULTAS

CREATE TABLE SERIEPLATAFORMA(
	COD_SERIE INT,
    COD_PLATAFORMA INT,
    FECHA_INCLUSION DATE,
    PRIMARY KEY(COD_SERIE, COD_PLATAFORMA)
);

-- EJECUTA EL SIGUIENTE CÓDIGO PARA QUE PUEDAS VACIAR LAS TABLAS AUNQUE ESTÉN RELACIONADAS 
-- Y LOS CAMPOS AUTOMÁTICOS SE REINICIEN.

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE SERIES;
TRUNCATE PERSONAJES;
TRUNCATE SERIEACTOR;
TRUNCATE SERIEPLATAFORMA;
TRUNCATE PLATAFORMAS;
TRUNCATE TEMPORADA;

SET FOREIGN_KEY_CHECKS = 1;

-- ------------------------------------------------------------------------
-- INSERT EN TABLAS
-- --------------------------------------------------------------------------

-- SERIES

INSERT INTO SERIES (NOMBRE_SERIE, GENERO, AÑO_ESTRENO)
VALUES
('Mundos Paralelos', 'CIENCIA FICCIÓN', '2020-01-01'),
('Risas en Casa', 'COMEDIA', '2018-01-01'),
('El Reino Oculto', 'FANTASÍA', '2019-01-01'),
('Hospital Central', 'DRAMA', '2005-01-01');


-- PERSONAJES (antes ACTORES)

INSERT INTO PERSONAJES 
VALUES
(1, 'Laura Martínez', '1990-04-12', 'ESPAÑOLA'),
(2, 'Carlos Ruiz', '1985-09-20', 'ARGENTINA'),
(3, 'Ana Torres', '1992-01-15', 'MEXICANA'),
(4, 'John Smith', '1980-07-30', 'ESTADOUNIDENSE');

--  TEMPORADAS

INSERT INTO TEMPORADA
VALUES
(1, 1, '2021-01-10 20:00:00'),
(1, 2, '2022-02-15 21:30:00'),
(2, 1, '2018-03-05 19:00:00'),
(3, 1, '2019-10-01 22:00:00'),
(4, 1, '2005-09-15 21:00:00'),
(4, 2, '2006-09-15 21:00:00');

-- SERIEACTOR

INSERT INTO SERIEACTOR (COD_SERIE, COD_ACTOR)
VALUES
(1, 1),
(1, 2),
(2, 3),
(3, 1),
(4, 4);

-- PLATAFORMAS

INSERT INTO PLATAFORMAS (COD_PLATAFORMA, NOMBRE_PLATAFORMA)
VALUES
(1, 'Netflix'),
(2, 'HBO Max'),
(3, 'Amazon Prime Video');

-- SERIEPLATAFORMA

INSERT INTO SERIEPLATAFORMA (COD_SERIE, COD_PLATAFORMA, FECHA_INCLUSION)
VALUES
(1, 1, '2020-05-01'),
(1, 2, '2021-01-01'),
(2, 1, '2019-01-01'),
(3, 3, '2020-10-10'),
(4, 1, '2005-10-01');

-- Muestra el nombre de las series y el nombre de los actores que intervienen en ellas.
SELECT S.NOMBRE_SERIE, P.NOMBRE_ACTOR
FROM SERIES S
INNER JOIN SERIEACTOR SA USING(COD_SERIE)
INNER JOIN PERSONAJES P USING(COD_ACTOR);

-- Muestra las series que tengan más de una temporada publicada.
SELECT S.NOMBRE_SERIE
FROM SERIES S
INNER JOIN TEMPORADA T USING(COD_SERIE)
GROUP BY S.NOMBRE_SERIE
HAVING COUNT(t.NUM_TEMPORADA) > 1;

-- Muestra las series que estén disponibles en más de una plataforma.
SELECT S.NOMBRE_SERIE
FROM SERIES S
INNER JOIN SERIEPLATAFORMA SP USING(COD_SERIE)
GROUP BY S.NOMBRE_SERIE
HAVING COUNT(SP.COD_PLATAFORMA) > 1;


-- Muestra los nombres de los actores que hayan participado en series del género 'FANTASÍA'.
SELECT P.NOMBRE_ACTOR
FROM PERSONAJES P
INNER JOIN SERIEACTOR SA USING(COD_ACTOR)
INNER JOIN SERIES S USING(COD_SERIE)
WHERE S.GENERO = 'FANTASÍA';

-- Muestra las series cuyo año de estreno sea mayor que el año medio de estreno de todas las series.
SELECT NOMBRE_SERIE
FROM SERIES
WHERE AÑO_ESTRENO > (SELECT AVG(AÑO_ESTRENO) FROM SERIES);

-- Muestra las series que tengan al menos una temporada estrenada después de 2021.
SELECT S.NOMBRE_SERIE
FROM SERIES S
INNER JOIN TEMPORADA T USING(COD_SERIE)
WHERE YEAR(t.FECHA_ESTRENO) > 2021;

-- Muestra los actores que hayan participado en series disponibles en la plataforma 'Netflix'.
SELECT P.NOMBRE_ACTOR
FROM PERSONAJES P
INNER JOIN SERIEACTOR SA USING(COD_ACTOR)
INNER JOIN SERIES S USING(COD_SERIE)
INNER JOIN SERIEPLATAFORMA SP USING(COD_SERIE)
INNER JOIN PLATAFORMAS PL USING(COD_PLATAFORMA)
WHERE PL.NOMBRE_PLATAFORMA = 'Netflix';

-- Muestra las series que no tengan ninguna temporada registrada.
SELECT S.NOMBRE_SERIE
FROM SERIES S
INNER JOIN TEMPORADA T USING(COD_SERIE)
WHERE T.COD_SERIE IS NULL;

-- Muestra la serie cuya temporada más reciente tenga la fecha de estreno más reciente.
SELECT S.NOMBRE_SERIE
FROM SERIES S
INNER JOIN TEMPORADA T USING(COD_SERIE)
ORDER BY T.FECHA_ESTRENO DESC
LIMIT 1;

-- Muestra los actores que han participado en series disponibles en más de una plataforma distinta.
SELECT P.NOMBRE_ACTOR
FROM PERSONAJES P
INNER JOIN SERIEACTOR SA USING(COD_ACTOR)
INNER JOIN SERIES S USING(COD_SERIE)
INNER JOIN SERIEPLATAFORMA SP USING(COD_SERIE)
GROUP BY P.COD_ACTOR, P.NOMBRE_ACTOR
HAVING COUNT(DISTINCT SP.COD_PLATAFORMA) > 1;