CREATE DATABASE PRUEBAAAAA;
USE PRUEBAAAAA;

DELIMITER //
DROP PROCEDURE IF EXISTS VAR_EJEMPLO1//
CREATE PROCEDURE VAR_EJEMPLO1()
BEGIN
	DECLARE VARIABLE1 INT;
	DECLARE VARIABLE2 VARCHAR(20);
    SET VARIABLE1=25;
    SET VARIABLE2='ESTO ES UNA PRUEBA';
    SELECT CONCAT_WS('*****', VARIABLE1, VARIABLE2) AS RESULTADO;
    SELECT CONCAT(VARIABLE1, '-----', VARIABLE2) AS RESULTADO2;
END;

//
DELIMITER ;
CALL VAR_EJEMPLO1();

DELIMITER //

DROP PROCEDURE IF EXISTS EJEMPLO_VAR1//
CREATE PROCEDURE EJEMPLO_VAR1()
BEGIN
	DECLARE V_1 INT DEFAULT 0;
    DECLARE V_2 VARCHAR(20);
    SELECT ID,NOMBRE FROM ALUMNOS
    WHERE ID=4 INTO V_1,V_2;
    SELECT V_1,V_2;
END;
//
DELIMITER ;
CALL EJEMPLO_VAR1();

DELIMITER //

DROP PROCEDURE IF EXISTS EJEMPLO_VAR2//
CREATE PROCEDURE EJEMPLO_VAR2()
BEGIN
	DECLARE V_1 INT DEFAULT 0;
    DECLARE V_2 VARCHAR(20);
    SELECT ID,NOMBRE INTO V_1,V_2 FROM ALUMNOS;
    SELECT V_1,V_2;
END;
//
DELIMITER ;
CALL EJEMPLO_VAR2();